spring.application.name=movies
spring.data.mongodb.database=movie-api-db
spring.data.mongodb.uri=mongodb+srv://aashishbedi0:Live%401ce@cluster0.edejyaz.mongodb.net/movie-api-db?retryWrites=true&w=majority